apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: ${DOCKER_REPO_NAME}
  labels:
    app: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: ${ECR_REGISTRY}/g5-slabai-payment:${TAG}
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NODE_ENV
        - name: PORT
          value: "3000"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGO_URI
        - name: RAZORPAY_KEY_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RAZORPAY_KEY_ID
        - name: RAZORPAY_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RAZORPAY_KEY_SECRET
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/payment/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/payment/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: ${DOCKER_REPO_NAME}
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
